syntax on

set hlsearch

" tab
set tabstop=4       " the width of <Tab>
set shiftwidth=4    " the width of >>, <<
set softtabstop=4   " <Backspace> delete 4 spaces
set expandtab

set autoindent


func SuperTab()
    if col('.') == 1 || getline('.')[col('.')-2] == ' ' || getline('.')[col('.')-2] == '\t'
        return "\<Tab>"
    else
        return "\<C-n>"
    endif
endfunc
inoremap <Tab> <c-r>=SuperTab()<CR>
